disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - for_where
    - multiple_closures_with_trailing_closure

opt_in_rules: # some rules are only opt-in
        - attributes
        - closure_spacing
        - fatal_error_message
        - file_header
        - first_where
        - nimble_operator
        - object_literal
        - operator_usage_whitespace
        - private_outlet
        - redundant_nil_coalescing
        - switch_case_on_newline

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - Build
    - VulcanBt/VulcanBt_iOS/Resources/GeneratedCode/
