language: swift
os: osx
osx_image: xcode9.3beta
before_script:
- gem install xcpretty
- java -jar server/bux-server.jar &>/dev/null &
script:
- set -o pipefail && xcodebuild -workspace Trade.xcworkspace -scheme Trade -destination "platform=iOS Simulator,name=iPhone 8,OS=11.2" -enableCodeCoverage YES clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
after_success:
- killall java -jar server/bux-server.jar
- bash <(curl -s https://codecov.io/bash) -J 'Trade'
